### ISSUE TITLE
Testing libraries?

### ISSUE THREAD

**Issue by Phyks** [shlomimatichin/Voodoo-Mock#16]
Hi,

I would like to monitor calls to an external library. Say, for instance,
```
#include <algorithm>

int foo(int a, int b) {
    return std::min(a,b);
}
```

And I would like to check that calling `foo(1,2)` actually returns 1, and calls `std::min` in between.

Is it possible to do it with Voodoo-Mock?

Thanks!

**Comment by shlomimatichin** [comment]
I will split my answer into several parts:

Selecting the unit under test:
--------------------------------------
I assume your question is general, not for this specific example. For this specific example, i would have designed the test differently, and would not have mocked std::min. In fact, this is true for most of STL (data structures and algorithms) - i usually keep them inside the unit under test, and don't mock them. My reasoning is that you want to test the algorithm as a whole, usually. Another example would be testing if an object has been deleted (destructor called), and not the specifics of how this smart pointer or that smart pointer have been used. This is usually "not interesting" as long as the pointer ownership contract is tested as part of the API for the unit under test. Another example would be a class that "computes" a running average/percentile over data. It's important to test that it works correctly, but it's not interesting if internally it uses a std::map or a std::queue -> thats testing implementation instead of behavior / contract.

Mocking functions of other libraries, Option #1:
--------------------------------------------------------------
Lately i found that almost any other library i use, i usually have some sort of an abstraction layer on top of it. A good example would be the Linux/POSIX API - i would usually wrap open/read/write/socket/send/recv with either a function with the same name that uses exceptions, or with a class in the theme of that project (e.g., "FileDescriptor", "BroadcastSocket"), which also usually export only the use cases needed for that project (e.g., all sockets are UDP/TCP, so no need to open a non AF_INET socket). In these cases my insight is that i want to unit-test the classes above this layer, and just skip unit-testing the abstraction layer. These tests usually end up just being "mirrors" of the code, and usually provide very little improvement in quality (though it is nice to have 100% coverage, if you have the time ;-). But as far as i can give you advice, i would suggest skipping those unit-tests, and then voodoo-multi already creates mocks for the abstraction layer, that is part of your code.

Mocking functions of other libraries, Option #2:
--------------------------------------------------------------
So some cases are just too extreme for the voodoo parser. Boost/STL is one case, but also, the windows API header files, are rather complex. In this case, voodoo-single.py, has a feature called --external. The concept is simple - usually, voodoo parses file X.h, and creates a mirror header voodoo/X.h which either mocks the API in X.h, or refers to it. Using --external, you can, header by header, make voodoo parse Other.h header file, instead of X.h. So the result will either mock the API exported by Other.h, or refer to X.h . Now all you need to do, is put into Other.h declarations (not implementation, just the function prototype) for all the functions from the complex headers you are trying to mock. Let me know if you are planning to use this feature, i will add a relevant example, but like i tried to explain, this is not the first choice for me.

Hope this helps,
Let me know how it goes,
Shlomi

**Comment by Phyks** [comment]
@shlomimatichin I agree my example was kind of artificial. My setup is I have some libraries and (indeed) some wrappers around them. I need to test codes calling this wrapper, to ensure it is calling the wrapper functions with the right arguments, so first option is ok for this.

But I should also test the wrapper itself as I should have 100% coverage (sadly =(). So I may give a try to option 2.

Ideally, my tests should be able to run with a cross-compiler (I tried to replace g++ by a CXX environment variable, and this part seems to be ok), on Windows and Linux, and integrate to the already used framework (Google Testing Framework).

I will play a bit with Voodoo and see how well it can fit, but it seems perfect for my use case, preventing me from writing useless wrappers and link seams. =)
